Algoritmo "SomaSimples"

Var
   num_um, num_dois, num_tres, soma: inteiro
   

Inicio
      escreval("Digite o primeiro número: ")
      leia(num_um)
      
      escreval("Digite o primeiro número: ")
      leia(num_dois)
      
      escreval("Digite o primeiro número: ")
      leia(num_tres)
      
      soma := num_um + num_dois + num_tres
      
      escreval("A soma é: ", soma)
      
      
Fimalgoritmo